### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ZekeZDev** [ZekeSmith/Illager-Expansion-Rematch#1]
- [ ] [Unable to Load fire_magic Model](https://github.com/ZekeSmith/Illager-Expansion-Archive/issues/1) (issue from illager-expansion-archive)
- [x] [Fix imbuing table PR for 1.18.2 ](https://github.com/ZekeSmith/Illager-Expansion-Archive/pull/2)
- [ ] Port imbuing table fix to 1.19.x
- [x] Update to support 1.19.1 and 1.19.2
- [ ] Rework firecaller belt

**Comment by IvanHarryDev** [comment]
Please Update to support 1.19.1 and 1.19.2

**Comment by PKPenguin321** [comment]
Maybe make platinum infused netherite tools do something instead of just being a reskin

**Comment by ZekeZDev** [comment]
Yeah deffinetly I am still debating what usage would make sense for them, feel free to share ideas if you have any.

**Comment by MLMII** [comment]
I'll be honest; I kind of like the idea of reskins because power creep in mods is a legitimate concern in my opinion, but if you want a functionality that is both useful and not a direct upgrade to netherite one could have the tools work like wings; at zero durability instead of breaking they simply stop working.
